name: "Testing PR"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing_pr:
    runs-on: macos-11
    name: Testing PR
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2'
      - name: checkout
        uses: actions/checkout@v2
      - name: show sdks
        run: xcodebuild -showsdks
      - name: testing 
        run: ./test_ios.sh
      - name: building
        run: ./build_ios.sh
